INSERT INTO public.questions (course_code, topic, question_text, options, correct_option_index, explanation, case_citation) VALUES 
('JPL 201', 'Formation of Contract', 'An invitation to treat is:', '["An offer that can be accepted", "A preliminary statement expressing a willingness to receive offers", "A binding legal contract", "An acceptance of an offer"]'::jsonb, 1, 'An invitation to treat is not an offer but a willingness to negotiate or receive offers.', 'Fisher v Bell'),
('JPL 201', 'Formation of Contract', 'Which of the following is the standard test for intention to create legal relations in commercial agreements?', '["Presumption of no intention", "Presumption of intention", "Subjective test of the parties", "Requirement of a written deed"]'::jsonb, 1, 'In commercial agreements, the law presumes an intention to create legal relations unless expressly rebutted.', 'Rose & Frank Co v JR Crompton & Bros Ltd'),
('JPL 201', 'Consideration', 'Past consideration is generally:', '["Valid and enforceable", "Invalid and not good consideration", "Valid only in written contracts", "Equivalent to executed consideration"]'::jsonb, 1, 'Past consideration is generally not good consideration as it was not given in exchange for the promise.', 'Re McArdle'),
('JPL 201', 'Offer and Acceptance', 'The postal rule states that acceptance is complete when:', '["The letter is received by the offeror", "The letter is posted, provided it is properly stamped and addressed", "The offeror reads the letter", "The offeree decides to accept"]'::jsonb, 1, 'Under the postal rule, acceptance takes effect the moment the letter of acceptance is posted.', 'Adams v Lindsell'),
('JPL 201', 'Consideration', 'Performance of an existing public duty is:', '["Good consideration", "Not good consideration unless it goes beyond the public duty", "Always sufficient", "An invitation to treat"]'::jsonb, 1, 'Merely doing what one is legally bound to do by public duty is not good consideration.', 'Collins v Godefroy'),

('PUL 201', 'Nature of the Constitution', 'A constitution that cannot be easily amended is known as:', '["Flexible", "Unwritten", "Rigid", "Federal"]'::jsonb, 2, 'A rigid constitution requires a special, usually difficult procedure for amendment.', ''),
('PUL 201', 'Rule of Law', 'According to A.V. Dicey, the Rule of Law includes all EXCEPT:', '["Supremacy of the law", "Equality before the law", "Immunity of the Executive", "Constitution is the result of ordinary law of the land"]'::jsonb, 2, 'Dicey''s concept emphasizes that no one is above the law, including the executive.', ''),
('PUL 201', 'Separation of Powers', 'The doctrine of Separation of Powers was prominently advocated by:', '["John Locke", "Montesquieu", "A.V. Dicey", "Thomas Hobbes"]'::jsonb, 1, 'Montesquieu formalized the doctrine of separation of powers in his work Spirit of the Laws.', ''),
('PUL 201', 'Federalism', 'In a federal system of government, power is:', '["Concentrated in the central government", "Shared between the central government and federating units", "Vested solely in the judiciary", "Delegated exclusively to local governments"]'::jsonb, 1, 'Federalism involves the division of powers between the central/federal government and regional/state governments.', ''),
('PUL 201', 'Constitutional Supremacy', 'Section 1(3) of the 1999 Constitution of Nigeria (as amended) provides that:', '["The President is supreme", "Any law inconsistent with the Constitution is void to the extent of the inconsistency", "The National Assembly can override the Constitution", "Customary law is supreme"]'::jsonb, 1, 'This establishes the supremacy of the Constitution over all other laws.', ''),

('PUL 203', 'Sources of Nigerian Law', 'Which of the following is NOT a primary source of Nigerian Law?', '["Received English Law", "Nigerian Legislation", "Textbooks and Law Journals", "Customary Law"]'::jsonb, 2, 'Textbooks and journals are secondary, persuasive sources of law, not primary binding sources.', ''),
('PUL 203', 'Court System', 'The highest court in the Nigerian judicial hierarchy is:', '["Court of Appeal", "Federal High Court", "Supreme Court of Nigeria", "National Industrial Court"]'::jsonb, 2, 'The Supreme Court is the apex court in Nigeria, whose decisions are final.', ''),
('PUL 203', 'Customary Law', 'For a custom to be valid and enforceable in Nigeria, it must pass the:', '["Repugnancy test", "Flexibility test", "Rigidity test", "Parliamentary test"]'::jsonb, 0, 'A custom must not be repugnant to natural justice, equity, and good conscience.', ''),
('PUL 203', 'Received English Law', 'The Received English Law in Nigeria consists of:', '["Common Law, Doctrines of Equity, and Statutes of General Application", "Only the Common Law", "Only Statutes of General Application", "Magna Carta and the Bill of Rights only"]'::jsonb, 0, 'Received English Law comprises the Common Law, Doctrines of Equity, and Statutes of General Application in force in England on Jan 1, 1900.', ''),
('PUL 203', 'Legal Profession', 'In Nigeria, the legal profession is fused, meaning:', '["Lawyers can only practice as Solicitors", "Lawyers can only practice as Barristers", "Legal practitioners act as both Barristers and Solicitors", "Lawyers must choose to be either a judge or an advocate"]'::jsonb, 2, 'Unlike England, Nigeria operates a fused profession where one is called to the bar as a Barrister and Solicitor of the Supreme Court.', '');
